model:
  name: RULMamba
  class_path: Models.RULMamba.RULMambaNetModel
  build_args:
    seq_len: 64
    pred_len: 1
    enc_in: 1
    c_out: 1
    d_model: 128
    n_dec_layer: 2
    dropout: 0.01
    expand: 2

loss:
  name: SMAPE
